# Label transform for forecasting with previous 2 days

In [1]:
import numpy as np

In [2]:

idx = np.random.randint(0, 10000)
print(idx)
days = list(range(idx-2,idx+1))
print(days)

6405
[6403, 6404, 6405]


In [5]:
list_a = [[1,2,3],[10,20,30]]
list_b = [[4,5,6,],[40,50,60]]
merged = np.column_stack([list_a,list_b])
print(merged)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]]


In [6]:
noise = np.concatenate(merged)
print(noise)

[ 1  2  3  4  5  6 10 20 30 40 50 60]


In [8]:
list = [1,2,3,4]
print(list[:-1])

[1, 2, 3]
